pipeline:
  name: Repro Branch Logic
  identifier: repro_branch_logic
  projectIdentifier: DoNotDelete_OM
  orgIdentifier: default
  properties:
    ci:
      codebase:
        repoName: templateRepo
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: repro_step
          versionLabel: v1