pipeline:
  name: Repro Branch Logic
  identifier: repro_branch_logic
  projectIdentifier: DoNotDelete_OM
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.harnessCode # This is the "bridge" to Harness Code
        repoName: templateRepo    # The name of your repo
        build: <+input>                  # Allows you to pick your branch at runtime
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sconnector
              namespace: default
          execution:
            steps:
              - step:
                  name: Run Template
                  identifier: run_template
                  template:
                    templateRef: repro_step
                    versionLabel: v1