pipeline:
  name: Repro Branch Logic
  identifier: repro_branch_logic
  projectIdentifier: DoNotDelete_OM
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.harnessCode # This is the "bridge" to Harness Code
        repoName: templateRepo    # The name of your repo
        build: <+input>                  # Allows you to pick your branch at runtime
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: repro_step # The identifier of your Stage Template
          versionLabel: v1
          templateInputs:
            type: CI # Required for CI stages
            # If your template has variables for the delegate, add them here:
            delegateSelectors:
              - k8s-delegate