pipeline:
  name: repro33491_P
  identifier: repro33491_P
  projectIdentifier: DoNotDelete_OM
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: refStep
                  identifier: refStep
                  template:
                    templateRef: repro33491_T
                    versionLabel: v1
