pipeline:
  name: Repro Branch Logic
  identifier: repro_branch_logic
  projectIdentifier: omtest
  orgIdentifier: default
  stages:
    - stage:
        name: custom
        identifier: custom
        tags: {}
        template:
          templateRef: customStage_Template
          versionLabel: v1
