pipeline:
  name: Repro Branch Logic
  identifier: repro_branch_logic
  projectIdentifier: proj1
  orgIdentifier: default
  stages:
    - stage:
        name: build
        identifier: build
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: temp
                  identifier: temp
                  template:
                    templateRef: temp
                    versionLabel: v1
