pipeline:
  name: PIPE-33491-pipeline
  identifier: PIPE33491pipeline
  projectIdentifier: DoNotDelete_OM
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: sg1
                  identifier: sg1
                  template:
                    templateRef: account.PIPE33491
                    versionLabel: v1
                    templateInputs:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            spec:
                              environmentVariables:
                                - name: hello
                                  type: String
                                  value: <+input>
        tags: {}
